title: MakerSmasher
description: Hacking, pentesting, reverse engineering and generally fun stuff.

url: https://www.makersmasher.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Projects
    url: /projects

social:
  github: makersmasher
  twitter: makersmasher
  email: anthony@makersmasher.com

google_analytics: "UA-188174387-1"

disqus:
    shortname: makersmasher
